import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import locaFont from "next/font/local"
import cocoFont from "next/font/local"

import "./globals.css";
import Navbar from "@/components/Navbar";




const poppins = Poppins({ 
  subsets: ["latin"], 
 
weight:"500", 
variable:'--font-poppins',
 });
 const gateway = locaFont({ src: "../assets/font/gatteway_signature/Gatteway Signature update.ttf",

variable:'--gatteway_signature',
 });
 const cocosharp = cocoFont({ src: "../assets/font/cocosharp/Coco-Sharp-Bold-trial.ttf",

 variable:'--coco_sharp',
  });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${(poppins.variable)} ${(gateway.variable)} ${(cocosharp.variable)} `}>
       
        {children}
        
        </body>
    </html>
  );
}
